# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# fstab configuration for btrfs
---
crypttabOptions: luks

mountOptions:
    - filesystem: default
      options: [ noatime ]
    - filesystem: btrfs
      options: [ noatime, "compress=zstd:3", "space_cache=v2", autodefrag ]
    - filesystem: btrfs_swap
      options: [ noatime ]
    - filesystem: efi
      options: [ "fmask=0137", "dmask=0027" ]
