#
# /etc/pacman.conf
# ArchCosta Build Configuration
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
ILoveCandy

SigLevel    = Never
LocalFileSigLevel = Optional

# ArchCosta Official Repository
[archcosta]
SigLevel = Optional TrustAll
Server = https://archcosta-os.github.io/x86_64/

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# CachyOS Repository (for linux-cachyos kernel)
[cachyos]
SigLevel = Never
Server = https://mirror.cachyos.org/repo/x86_64/cachyos
