[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel    = Never
LocalFileSigLevel = Optional

# ArchCosta Custom Repo (LOCAL FIRST)
[archcosta]
SigLevel = Optional TrustAll
Server = file:///home/ram/Music/arch/local-repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Linexin Repo (Keep as fallback)
[linexin-repo]
SigLevel = Optional TrustAll
Server = https://petexy.github.io/linexin-repo/x86_64
