[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[cachyos]
Server = https://mirror.cachyos.org/repo/$arch/$repo
SigLevel = Optional TrustAll

[cachyos-extra-v3]
Server = https://mirror.cachyos.org/repo/$arch/$repo
SigLevel = Optional TrustAll

[cachyos-core-v3]
Server = https://mirror.cachyos.org/repo/$arch/$repo
SigLevel = Optional TrustAll

[archcosta]
Server = https://archcosta-os.github.io/archcosta-pkgbuilds/
SigLevel = Optional TrustAll
