[main]
font=JetBrains Mono:size=10.5
shell=/usr/bin/bash
pad=8x4
dpi-aware=yes

[cursor]
blink=yes
style=block

[colors]
background=1a1025
foreground=e0d0e8

## Normal colors
regular0=1a1025
regular1=c0568b
regular2=50a070
regular3=d4a060
regular4=7080c0
regular5=b060a0
regular6=5090a0
regular7=e0d0e8

## Bright colors
bright0=b0a0b8
bright1=d070a0
bright2=70c090
bright3=e0c080
bright4=90a0e0
bright5=d080c0
bright6=70b0c0
bright7=f0e8f0

[key-bindings]
clipboard-paste=Control+Shift+v
clipboard-copy=Control+Shift+c
primary-paste=Shift+Insert
