#
# LightDM Configuration for ArchCosta
#

[LightDM]
# Minimum VT
minimum-vt=1

# Autologin - no password required
autologin-user=live
autologin-user-timeout=0
autologin-guest=false
autologin-session=
pam-autologin-service=lightdm-autologin

[Seat:*]
# Greeter
greeter-session=lightdm-slick-greeter
greeter-hide-users=false

# User session (will be set per-ISO by build script)
user-session=xfce

# Allow user switching
allow-user-switching=true
allow-guest=false

# X server
xserver-command=X -core -nolisten tcp
