#!/bin/sh
# Hyprland autostart for Live user

# Set XDG variables
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

# Start Hyprland
exec Hyprland
