# Mango WM Configuration for ArchCosta
# Reference: https://github.com/DreamMaoMao/mango/wiki/

###############  Autostart on boot  ###############
source=./Autostart.conf
##################################################

###############  General settings  ################
source=./General.conf
##################################################

###############  Environment variables  ###########
source=./Environments.conf
##################################################

###############  Animations settings  #############
source=./Animations.conf
##################################################

###############  Blur settings  ###################
source=./Blur.conf
##################################################

###############  Shadows settings  ################
source=./Shadows.conf
##################################################

###############  Scroller layout  #################
source=./Scroller_layout.conf
##################################################

###############  Master-Stack layout  #############
source=./Master-Stack.conf
##################################################

###############  Dwindle layout  ##################
source=./Dwindle_layout.conf
##################################################

###############  Keybinds  ########################
source=./Keybinds.conf
##################################################

###############  Window and layer rules  ##########
source=./Rules.conf
##################################################

###############  Tagrules  ########################
source=./Tagrules.conf
##################################################
