# Wayland session
env=XDG_SESSION_TYPE,wayland
env=GDK_BACKEND,wayland,x11
env=CLUTTER_BACKEND,wayland

# Qt
env=QT_QPA_PLATFORM,Wayland;xcb
env=QT_AUTO_SCREEN_SCALE_FACTOR,1

# Firefox
env=MOZ_ENABLE_WAYLAND,1

# Electron apps
env=ELECTRON_OZONE_PLATFORM_HINT,auto
