# Window rules
windowrule=focused_opacity:0.85,appid:foot
windowrule=unfocused_opacity:0.75,appid:foot
windowrule=isfloating:1,appid:[Ss]team
windowrule=isfloating:0,title:Steam
windowrule=isfloating:1,appid:steam,title:Steam Settings

windowrule=title:Authentication required,isfloating:1
windowrule=title:Keybindings,isfloating:1
windowrule=title:Rename*,isfloating:1
windowrule=title:File Operation Progress*,isfloating:1
windowrule=title:Confirm to replace files*,isfloating:1
windowrule=title:Extracting Files*,isfloating:1
windowrule=appid:thunar,offsety:96%,offsetx:98%,isfloating:1,width:860,height:520
windowrule=appid:nmtui,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:580
windowrule=offsety:96%,offsetx:98%,isnoborder:1,isopensilent:1,isoverlay:1,isfloating:1,width:440,height:220,title:Picture-in-Picture
windowrule=offsety:96%,offsetx:98%,isnoborder:1,isopensilent:1,isoverlay:1,isfloating:1,width:440,height:220,title:Picture in picture

# Layer rules
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
layerrule=noanim:1,noblur:1,layer_name:selection
