# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# partition handling.
---

efi:
    mountPoint:         "/efi"
    recommendedSize:    2048MiB
    minimumSize:        500MiB
    label:              "EFI"

userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
    - file      # To swap file instead of partition

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType:  "btrfs"
showNotEncryptedBootMessage:   false
luksGeneration: luks1

availableFileSystemTypes:  ["ext4","btrfs"]

partitionLayout:
    - name: "archcosta"
      filesystem: "btrfs"
      mountPoint: "/"
      size: 100%

# Included here as requested, though typically used by mount module in Calamares
btrfsSubvolumes:
    - mountPoint: /
      subvolume: /@
    - mountPoint: /home
      subvolume: /@home
    - mountPoint: /var/cache
      subvolume: /@cache
    - mountPoint: /var/log
      subvolume: /@archcosta-repo/x86_64/archcosta-log-tool-1.0-1-any.pkg.tar.zst
