# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Custom post-install shell operations
---
dontChroot: false
timeout: 999
script:
    - command: "/usr/bin/dracut --force --regenerate-all"
    - command: "/usr/bin/grub-mkconfig -o /boot/grub/grub.cfg"
    - command: "/usr/bin/systemctl enable grub-btrfsd.service"
