# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration file for ArchCosta installs
---
modules-search: [ local ]

instances:
- id:       archcosta
  module:   shellprocess
  config:   shellprocess.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - dracut
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - initramfs
  - bootloader
  - services-systemd
  - shellprocess@archcosta
  - umount
- show:
  - finished

branding: archcosta

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: true

quit-at-end: false
